services:
  dotnet:
    build:
      context: .
      dockerfile: Dockerfile   # Optional if your Dockerfile is named "Dockerfile"  
    container_name: bridge-mall-app
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mysql
    volumes:
      - ./dataprotection:/home/app/.aspnet/DataProtection-Keys


  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=#secured
      - MYSQL_DATABASE=bridge-mall_db
      - MYSQL_USER=rodern
      - MYSQL_PASSWORD=#secured
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
