services:
  dotnet:
    build:
      context: .
      dockerfile: Dockerfile   # Optional if your Dockerfile is named "Dockerfile"  
    container_name: dotnet-app
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=#secured
      - MYSQL_DATABASE=bridge-maill_db
      - MYSQL_USER=rodern
      - MYSQL_PASSWORD=#secured
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
